In [3]:
from random import seed
from random import randrange
from math import exp
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.model_selection import KFold

In [4]:
sample = [100,200,300,400,500,600,700,800,900,100,110,120]
kf = KFold(n_splits=3)

for train_index, test_index in kf.split(sample):
    print (train_index, test_index)

[ 4  5  6  7  8  9 10 11] [0 1 2 3]
[ 0  1  2  3  8  9 10 11] [4 5 6 7]
[0 1 2 3 4 5 6 7] [ 8  9 10 11]


In [5]:
dataset=pd.read_csv('Student-University(For Logistic Regression Program).csv')
X = dataset.iloc[:,:-1]
#X=np.array(list(zipped)).tolist()
Y=dataset.iloc[:,-1]
dataset.head()
X
Y

0     0
1     0
2     1
3     1
4     0
     ..
94    1
95    1
96    1
97    1
98    1
Name: 0, Length: 99, dtype: int64

In [6]:
from sklearn import preprocessing
X1 = preprocessing.scale(X)
df = pd.DataFrame(X1, columns =['marks1','marks2'])
print(df)

      marks1    marks2
0  -1.857446 -1.197540
1  -1.567891  0.366654
2  -0.300715  1.089583
3   0.680844  0.498347
4  -1.086963 -0.527726
..       ...       ...
94  0.912898 -0.955674
95 -1.233887  1.132469
96  1.736977  0.144120
97 -0.552877 -0.063137
98  0.459183  1.263287

[99 rows x 2 columns]


In [7]:
from sklearn.model_selection import KFold 
kf = KFold(n_splits=5) 

In [8]:
for train_index , test_index in kf.split(X1):
    xtrain , xtest = df.iloc[train_index,:],df.iloc[test_index,:]
    ytrain , ytest = Y[train_index] , Y[test_index]
    ytrain=list(ytrain)
    x1=list(xtrain["marks1"].values)
    x2=list(xtrain["marks2"].values)
    b0=0.0
    b1=0.0
    b2=0.0
    alpha=0.01
    prediction=[]
    epoch=10000
    for j in range(epoch):
        for i in range(len(xtrain)):
            pred=1/(1+np.exp(-(b0+b1*x1[i]+b2*x2[i])))
            error=ytrain[i]-pred
            cons=1-pred
            b0=b0+(alpha*error*pred*cons*1)
            b1=b1+(alpha*error*pred*cons*x1[i])
            b2=b2+(alpha*error*pred*cons*x2[i])
print(b0)
print(b1)
print(b2)

1.6271932011939996
3.9674493684100556
3.27721129756741


In [9]:
x1test=list(xtest["marks1"].values)
x2test=list(xtest["marks2"].values)
prediction1=[]
for i in range(len(xtest)):
    pred1=1/(1+np.exp(-(b0+b1*x1test[i]+b2*x2test[i])))
    print(pred1)
    prediction1.append(pred1)

0.9817704274895959
0.8802169267411492
0.20777464226474826
0.9998762145485781
0.9962807166111556
0.2582885446490442
0.9996264720203796
0.9999352053049915
0.10650519241387853
0.9999167769708741
0.9999716179734917
0.002644502768428775
0.9987738495892841
0.9476634520987363
0.8925565819093915
0.609008899812422
0.9998754743561297
0.3157808932042753
0.9994942886339893


In [10]:
for i in range(len(prediction1)):
    prediction1[i]=round(prediction1[i])

In [11]:
prediction1



[1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1]

In [12]:

ytest



80    1
81    1
82    1
83    1
84    1
85    0
86    1
87    1
88    0
89    1
90    1
91    0
92    1
93    1
94    1
95    1
96    1
97    1
98    1
Name: 0, dtype: int64

In [13]:

from sklearn.metrics import accuracy_score
print(accuracy_score(ytest,prediction1))


0.8947368421052632


In [14]:
import pandas as pd
import numpy as np
#importing the dataset into kaggle
df = pd.read_csv("Student-University(For Logistic Regression Program).csv")
df.drop("Name",axis=1,inplace=True)
df.drop("Ticket",axis=1,inplace=True)
df.drop("PassengerId",axis=1,inplace=True)
df.drop("Cabin",axis=1,inplace=True)
df.drop("Embarked",axis=1,inplace=True)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])
newdf=df
newdf
#splitting the data into x and y
y = df['Survived']
df.drop("Survived",axis=1,inplace=True)
df.info()
print(df.isnull().sum())
import copy
updated_df = copy.deepcopy(df)
updated_df['Age']=updated_df['Age'].fillna(updated_df['Age'].mean())
updated_df.info()
print(updated_df.isnull().sum())
print(df.isnull().sum())
updated_df1 = df
updated_df1['Ageismissing'] = updated_df1['Age'].isnull()
updated_df1.info()
from sklearn.impute import SimpleImputer
my_imputer = SimpleImputer(strategy = 'median')
data_new = my_imputer.fit_transform(updated_df1)
updated_df1.info()


KeyError: "['Name'] not found in axis"